ridecasa/activity/views.py
import itsdangerous
from average import EWMA
from flask import abort, Blueprint, current_app, redirect, render_template, request
from flask_login import current_user, login_required
from pony.orm import db_session
from pony import orm
from ridecasa.models import db
from ridecasa.sportdata import ActivitySummary, TrackData
from ridecasa import cache
from ridecasa.util import geohash_decode, haversine_distance_meters
from ridecasa.activity.forms import ActivityChartAxisForm


activity_blueprint = Blueprint('activity', __name__,
                               template_folder='templates')


@activity_blueprint.route('/activity/<int:activity_id>', methods=['GET', 'POST'])
@login_required
@db_session
def activity(activity_id):
    chart_axis_form = ActivityChartAxisForm()
    user_pref = orm.select(u for u in db.UserPref
                           if u.user == current_user).first()
    chart_axis = user_pref.activity_chart_axis
    if not chart_axis:
        chart_axis = 'distance'
    if request.method == 'POST':
        if 'shareButton' in request.form:
            token = request.form['shareButton']
            serializer = itsdangerous.serializer.Serializer(
                current_app.config['SECRET_KEY'])
            token_data = serializer.loads(itsdangerous.encoding.base64_decode(token))
            activity = db.Activity.get(activity_id=token_data['activity_id'])
            if activity.user != current_user:
                # POST to an activity not owned by current user
                abort(500)
            activity.public = not activity.public
        elif chart_axis_form.data and chart_axis_form.validate():
            if request.form['axis'] not in ['time', 'distance']:
                abort(500)
            chart_axis = request.form['axis']
            user_pref.activity_chart_axis = chart_axis

    return render_activity_page(current_user, activity_id, owned=True,
                                chart_axis=chart_axis)


@activity_blueprint.route('/activity/<token>', methods=['GET', 'POST'])
@db_session
def shared_activity(token):
    serializer = itsdangerous.serializer.Serializer(current_app.config['SECRET_KEY'])
    token_data = serializer.loads(itsdangerous.encoding.base64_decode(token))
    user = db.User.get(id=token_data['user_id'])
    if user == current_user:
        return redirect('/activity/' + str(token_data['activity_id']))

    # guard against displaying any activity that may have been shared
    # previously but is no longer
    activity_status = orm.select((a.public, a.public_token) for a in db.Activity
                                 if a.activity_id == token_data['activity_id']
                                 and a.user.id == token_data['user_id']).first()
    if not activity_status:
        abort(404)
    public, activity_token = activity_status
    if not public or activity_token != token:
        abort(404)

    chart_axis = 'distance'
    chart_axis_form = ActivityChartAxisForm()
    if request.method == 'POST':
        if chart_axis_form.data and chart_axis_form.validate():
            chart_axis = request.form['axis']

    return render_activity_page(user, token_data['activity_id'], owned=False,
                                chart_axis=chart_axis)


@db_session
def render_activity_page(user, activity_id, owned=False, chart_axis=None):  # noqa: C901
    try:
        int(activity_id)
    except ValueError:
        abort(404)
    if not db.Activity.exists(activity_id=activity_id):
        abort(404)

    # honor privacy geofence if user sharing activity has set one
    user_pref = orm.select(u for u in db.UserPref
                           if u.user == user).first()
    geofence_coord = None
    if user_pref.geofence_geohash:
        geofence_coord = geohash_decode(user_pref.geofence_geohash)
    geofence_radius_meters = user_pref.geofence_radius_meters
    # don't enable geofence if user owns activity
    geofence_enabled = user_pref.geofence_enabled and not owned

    activity = db.Activity.get(activity_id=activity_id)
    chart_axis_form = ActivityChartAxisForm()

    # shared activity should use geofence info for cache so it's invalid if
    # the geofence changes before the cache expires
    shared_key = ''
    if not owned:
        shared_key = str(geofence_coord) + str(geofence_radius_meters)
    cache_trackpoints_list_key = '_'.join(['trackpoints', user.username,
                                           str(activity_id), str(owned),
                                           shared_key])
    cache_tp_segments_key = '_'.join(['tp_segments', user.username,
                                      str(activity_id), str(owned), shared_key])
    cache_summary_key = '_'.join(['summary', user.username, str(activity_id),
                                  str(owned), shared_key])
    if activity.user != user:
        abort(404)
    # Note: most of the activity summary data is generated as trackpoints are
    # iterated below
    summary = cache.get(cache_summary_key)
    tp_cnt = 0
    speed_cnt = 0
    hr_cnt = 0
    cadence_cnt = 0
    prev_alt = 0
    tp_list = cache.get(cache_trackpoints_list_key)
    tp_segment_indexes = cache.get(cache_tp_segments_key)
    if not tp_list and not summary:
        tp_list = []
        tp_segment_indexes = set()
        idx = 0
        calories = int(activity.calories) if activity.calories else None
        summary = ActivitySummary(distanceMeters=round(activity.distanceMeters, 1),
                                  totalTimeSecs=0, startTime=activity.startTime,
                                  timezone=activity.timezone, sport=activity.sport,
                                  calories=calories)
        # collect trackpoints for activity. It's important that trackpoints are
        # sorted here since the activity summary is derived while parsing them,
        # and some attributes (like speed) depend on previous trackpoints
        trackpoints = activity.trackpoints.sort_by(db.TrackPoint.startOffsetSeconds)
        avg_altitude = EWMA(beta=0.99)
        cadence_ewma = EWMA(beta=0.85)
        # set to True in case the first trackpoint is in the geofence
        in_fence = True
        prev_in_fence = True
        for t in list(trackpoints):
            td = TrackData(startOffsetSeconds=t.startOffsetSeconds,
                           geohash=t.geohash, altitudeMeters=t.altitudeMeters,
                           distanceMeters=t.distanceMeters, heartrate=t.heartrate,
                           speed=round(t.speed, 2), cadence=t.cadence)
            if not summary.avg_speed and td.speed:
                summary.avg_speed = td.speed
            elif td.speed:
                summary.avg_speed = (((summary.avg_speed * speed_cnt) + td.speed)
                                     / (speed_cnt + 1))
            if not summary.avg_hr and td.heartrate:
                summary.avg_hr = td.heartrate
            elif td.heartrate:
                summary.avg_hr = (((summary.avg_hr * hr_cnt) + td.heartrate)
                                  / (hr_cnt + 1))
            if not summary.avg_cadence and td.cadence:
                summary.avg_cadence = td.cadence
            elif td.cadence:
                td.cadence = cadence_ewma.update(td.cadence)
                summary.avg_cadence = (((summary.avg_cadence * cadence_cnt)
                                        + td.cadence) / (cadence_cnt + 1))
            if td.speed:
                speed_cnt += 1
            if td.heartrate:
                hr_cnt += 1
            if td.cadence:
                cadence_cnt += 1
            alt = avg_altitude.update(td.altitudeMeters)
            if prev_alt:
                alt_diff = alt - prev_alt
                if alt_diff > 0:
                    summary.alt_gain += alt_diff
            prev_alt = alt
            tp_cnt += 1
            # round speed less than 1km/hr to 0 since speed calc isn't that
            # accurate anyways
            if td.speed < 1.0:
                td.speed = 0
            if td.speed > summary.max_speed:
                summary.max_speed = td.speed
            if td.heartrate > summary.max_hr:
                summary.max_hr = td.heartrate
            if summary.min_hr == 0 or td.heartrate < summary.min_hr:
                summary.min_hr = td.heartrate
            if summary.min_ele == 0 or td.altitudeMeters < summary.min_ele:
                summary.min_ele = td.altitudeMeters
            if summary.max_ele == 0 or td.altitudeMeters > summary.max_ele:
                summary.max_ele = td.altitudeMeters
            # save index for start of a track segment, for use when drawing
            # around the privacy geofence
            if geofence_enabled and geofence_coord:
                distance = haversine_distance_meters(geofence_coord, (td.lat, td.lon))
                in_fence = distance <= geofence_radius_meters
                if not in_fence and prev_in_fence:
                    # start of new track segment
                    tp_segment_indexes.add(idx)
                prev_in_fence = in_fence
                if in_fence:
                    continue
            tp_list.append(td)
            idx += 1

    # segment indexes need to be sorted so tracks are drawn correctly
    if tp_segment_indexes is None:
        # initialize so that jinja's tojson gives an empty array
        tp_segment_indexes = []
    else:
        tp_segment_indexes = list(tp_segment_indexes)
        tp_segment_indexes.sort()
    summary.avg_hr = round(summary.avg_hr)
    summary.avg_speed = round(summary.avg_speed)
    summary.avg_cadence = round(summary.avg_cadence)
    summary.totalTimeSecs = activity.totalTimeSecs
    show_hr_chart = summary.avg_hr != 0
    show_cadence_chart = summary.avg_cadence != 0
    # timeout = 1 day
    cache.set(cache_trackpoints_list_key, tp_list, timeout=86400)
    cache.set(cache_summary_key, summary, timeout=86400)
    cache.set(cache_tp_segments_key, tp_segment_indexes, timeout=86400)
    if not chart_axis:

ridecasa/settings/views.py
import itsdangerous
from flask import (abort, Blueprint, current_app, flash, redirect, request,
                   render_template)
from flask_login import (current_user, login_required, logout_user)
from pony.orm import db_session
from pony import orm
from ridecasa.models import db
from ridecasa import bcrypt
from ridecasa.settings.forms import (SettingsSecurityForm, SettingsDeleteUserForm,
                                     SettingsPrivacyGeofenceForm)
from ridecasa.tasks import delete_user
from ridecasa.util import geohash_decode, geohash_encode, remove_parens


settings_blueprint = Blueprint('settings', __name__,
                               template_folder='templates')


@settings_blueprint.route('/privacy', methods=['GET', 'POST'])
@db_session
@login_required
def privacy():
    shared_activities = orm.select(a for a in db.Activity
                                   if a.user == current_user
                                   and a.public is True)
    user_pref = orm.select(u for u in db.UserPref
                           if u.user == current_user).first()

    geofence_geohash = user_pref.geofence_geohash
    geofence_radius_meters = user_pref.geofence_radius_meters
    geofence_enabled = user_pref.geofence_enabled

    if not geofence_radius_meters:
        geofence_radius_meters = 100
    geofence_coord = None
    if geofence_geohash:
        geofence_coord = geohash_decode(geofence_geohash)
    geofence_form = SettingsPrivacyGeofenceForm(coord=str(geofence_coord),
                                                radius=geofence_radius_meters / 1000)
    if request.method == 'POST':
        # user clicked 'unshare' on an activity
        if 'shareButton' in request.form:
            token = request.form['shareButton']
            serializer = itsdangerous.serializer.Serializer(current_app.config['SECRET_KEY'])  # noqa: E501
            token_data = serializer.loads(itsdangerous.encoding.base64_decode(token))
            activity = db.Activity.get(activity_id=token_data['activity_id'])
            if activity.user != current_user:
                # POST to an activity not owned by current user
                abort(500)
            activity.public = False
        # save geofence was submitted
        elif ('submit_geofence' in request.form and geofence_form.data
                and geofence_form.validate()):
            lat, lng = remove_parens(geofence_form.geofence_coord.data).split(',')
            geofence_coord = (float(lat), float(lng))
            ghash = geohash_encode(geofence_coord[0], geofence_coord[1])
            geofence_radius_meters = float(geofence_form.geofence_radius.data * 1000)
            user_pref.geofence_radius_meters = geofence_radius_meters
            user_pref.geofence_geohash = ghash
            user_pref.geofence_enabled = True
        # button to remove geofence was submitted
        elif 'remove_geofence' in request.form:
            geofence_coord = ''
            geofence_enabled = False
            # default to 0.1km
            geofence_radius_meters = 100
            user_pref.geofence_radius_meters = geofence_radius_meters
            user_pref.geofence_geohash = ''
            user_pref.geofence_enabled = False

    return render_template('settings/privacy.html', selected_tab='privacy',
                           geofence_form=geofence_form,
                           geofence_coord=geofence_coord,
                           geofence_radius_meters=geofence_radius_meters,
                           geofence_enabled=geofence_enabled,
                           shared_activities=shared_activities)


@settings_blueprint.route('/security', methods=['GET', 'POST'])
@db_session
@login_required
def security():
    form = SettingsSecurityForm(email=current_user.email)
    if request.method == 'POST':
        email = form.email.data
        if not form.validate_on_submit():
            return render_template('settings/security.html', form=form,
                                   selected_tab='security')
        if (orm.select(u for u in db.User if u.email == email).limit(1)
                and email != current_user.email):
            flash('This email address is already registered with an '
                  'account here.', 'error')
            return render_template('settings/security.html', form=form,
                                   selected_tab='security')
        if email != current_user.email:
            current_user.email = email
            flash('Email address updated', 'success')
        if form.new_password.data:
            new_pass = bcrypt.generate_password_hash(
                form.new_password.data).decode('utf-8')
            if not bcrypt.check_password_hash(current_user.password,
                                              form.current_password.data):
                flash('Current password is incorrect.', 'error')
                return render_template('settings/security.html', form=form,
                                       selected_tab='security')
            current_user.password = new_pass
            flash('Password updated', 'success')

    return render_template('settings/security.html', form=form,
                           selected_tab='security')


@settings_blueprint.route('/general', methods=['GET', 'POST'])
@db_session
@login_required
def general():
    form = SettingsDeleteUserForm()
    if request.method == 'POST':
        if not form.validate_on_submit():
            return render_template('settings/general.html', form=form,
                                   selected_tab='general')

        if not bcrypt.check_password_hash(current_user.password,
                                          form.current_password.data):
            flash('Current password is incorrect.', 'error')
            return render_template('settings/general.html', form=form,
                                   selected_tab='general')

        # schedule task to delete user later
        delete_user(current_user.id)
        # mark user as not enabled, since delete may not be instant
        user = db.User.get(id=current_user.id)
        user.enabled = False

        logout_user()
        return redirect('/login')
    return render_template('settings/general.html', form=form,
                           selected_tab='general')

ridecasa/templates/settings/general.html
{% extends "settings/layout.html" %}
{% block settings_content %}
<div class="section">
  <div class="field is-grouped is-grouped-centered">
    <form action="" method="post" novalidate>
      <div class="section">
        <h3 class="title is-3 is-spaced">
          <span>Here Be Dragons</span>
        </h3>
        <hr>
        <h5 class="title is-5 is-spaced">
          <span>Delete Account</span>
        </h5>
        <div class="field">
          <div class="label">
            {{ form.current_password.label }}
          </div>
          <div class="control">
            {{ form.current_password(size=32, class_="input") }}
          </div>
          {% for error in form.current_password.errors %}
          <span style="color: red;">{{ error }}</span>
          {% endfor %}
        </div>
        <div class="field">
          <div class="label">
            {{ form.i_am_sure.label }}
          </div>
          <div class="control">
            {{ form.i_am_sure(size=32, class_="input") }}
          </div>
          {% for error in form.i_am_sure.errors %}
          <span style="color: red;">{{ error }}</span>
          {% endfor %}
        </div>
      </div>
      <span>Note: This is permanent, there is no way to recover a deleted account.</span>
      <div class="field has-addons has-addons-right">
        <div class="control has-addons has-addons-right">
          {{ form.submit(class_="button is-link") }}
        </div>
      </div>
      {{ form.hidden_tag() }}
      {% with messages = get_flashed_messages(with_categories=True) %}
      {% if messages %}
      {% for category, message in messages %}
      <div class="label flash_{{category}}">{{ message }}</div>
      {% endfor %}
      {% endif %}
      {% endwith %}
    </form>
  </div>
</div>
{% endblock %}

ridecasa/templates/settings/layout.html
{% extends "layout.html" %}
{% block head %}
{% endblock %}

{% block content %}
<section class="section">
  <div class="tabs">
    <ul>
      <li {% if selected_tab == "general" %}class="is-active"{% endif %}><a href="{{ url_for('settings.general') }}">General</a></li>
      <li {% if selected_tab == "privacy" %}class="is-active"{% endif %}><a href="{{ url_for('settings.privacy') }}">Privacy</a></li>
      <li {% if selected_tab == "security" %}class="is-active"{% endif %}><a href="{{ url_for('settings.security') }}">Security</a></li>
    </ul>
  </div>
</section>
{% block settings_content %}
{% endblock %}
{% endblock %}

ridecasa/templates/settings/privacy.html
{% extends "settings/layout.html" %}
{% block head %}
    <link rel="stylesheet" href={{ url_for('static',filename='css/leaflet.css') }}>
    <script type="text/javascript" src="/static/js/leaflet.js" nonce="{{ csp_nonce() }}"></script>
    <script type="text/javascript" src="/static/js/leaflet-gesture-handling.min.js" nonce="{{ csp_nonce() }}"></script>
    <link rel="stylesheet" href={{ url_for('static',filename='css/leaflet-gesture-handling.min.css') }}>
{% endblock %}

{% block settings_content %}
<div class="section">
  <div class="is-grouped is-grouped-centered">
    {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="label flash_{{category}}">{{ message }}</div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    <div class="section">
      <h5 class="title is-5 is-spaced">
        <span>Publicly Shared Activities</span>
      </h5>
      {% if shared_activities %}
      <table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
        <thead>
          <tr>
            <th>Activity Name</th>
            <th>Sport</th>
            <th></th>
          </tr>
        </thead
        {% for activity in shared_activities %}
        <tr>
          <th><a href="{{url_for('activity.activity', activity_id=activity.activity_id)}}">{{activity.name}}</a></th>
          <th>{{activity.sport}}</th>
          <th>
            <form action="" method="post">
              <button name="shareButton" class="button is-danger is-small" type="submit" value="{{ activity.public_token }}">Unshare</button>
            </form>
          </th>
        </tr>
        {% endfor %}
      </table>
      {% else %}
      <h6 class="is-6 is-spaced">There are no shared activites.</h6>
      {% endif %}
    </div>
  </div>
  <div class="section">
    <div class="is-grouped is-grouped-centered">
      <h5 class="title is-5 is-spaced">
        <span>Privacy Geofence for Shared Activities</span>
      </h5>
      <span >Select a point on the map and a radius to have location data in this area removed from any activities that are shared publicly.</span>
      <div id="geofence_mapid" style="height:480px; z-index:1; margin-top: 2em" class="box"></div>
      <form action="" method="post" novalidate style="margin-top: 2em">
        <div id="radius_control_field" class="field centered">
          <div class="label">
            {{ geofence_form.geofence_radius.label }}
          </div>
          <div id='radius_value_label'>{{ geofence_radius_meters / 1000 }} km</div>
          <div class="control">
            {{ geofence_form.geofence_radius(size=32, min=0.1, max=5, step=0.1, value=geofence_radius_meters / 1000) }}
          </div>
          {% for error in geofence_form.geofence_radius.errors %}
          <span style="color: red;">{{ error }}</span>
          {% endfor %}
        </div>
        <div>
          {{ geofence_form.geofence_coord(value=geofence_coord) }}
        </div>
        <div class="field centered">
          <div id='geofence_submit_field' class="field">
            {{ geofence_form.submit_geofence(class_="button is-link") }}
          </div>
          {% if geofence_enabled %}
          <div class="field">
            {{ geofence_form.remove_geofence(class_="button is-link is-danger") }}
          </div>
          {% endif %}
        </div>
      </form>
    </div>
  </div>
</div>

<script nonce="{{ csp_nonce() }}">
  L.Icon.Default.imagePath = "{{ url_for('static', filename='img/') }}";
  var geofence_map = L.map('geofence_mapid', {
    zoomDelta: 0.25,
    zoomSnap: 0,
    gestureHandling: true
  });
	var osmUrl='https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
	var osmAttrib='Map data © <a href="https://openstreetmap.org">OpenStreetMap</a> contributors';
	var osm = new L.TileLayer(osmUrl, {attribution: osmAttrib});
	geofence_map.addLayer(osm);

  var geofence_submit_btn = $("#geofence_submit_field");
  var geofence_radius_input = $("#radius_control_field");
  var geofence_coord_input = $("#geofence_coord");

  var geofence_circle = L.circle([0, 0], {
    color: 'red',
    fillColor: '#e05',
    fillOpacity: 0.1,
    radius: {{ geofence_radius_meters if geofence_enabled else 100 }}
  });
  geofence_submit_btn.hide();
  {% if not geofence_coord[0] %}
  geofence_map.fitWorld();
  var geofence_center_marker = L.marker([0, 0]);
  geofence_radius_input.hide();
  {% else %}
  var existing_coord = [{{ geofence_coord[0]|string + ', ' + geofence_coord[1]|string }}];
  var geofence_center_marker = L.marker([{{geofence_coord[0]|string + ', ' + geofence_coord[1]|string}}]).addTo(geofence_map);
  geofence_circle.setLatLng(existing_coord);
  geofence_circle.addTo(geofence_map)
  geofence_radius_input.show();
  geofence_map.setView(existing_coord, 14)
  geofence_map.fitBounds(geofence_circle.getBounds());
  {% endif %}

  // map events
  geofence_map.on('click', function onMapClick(e) {
    geofence_center_marker.setLatLng(e.latlng);
    geofence_center_marker.addTo(geofence_map);
    geofence_circle.setLatLng(e.latlng);
    geofence_circle.addTo(geofence_map);
    geofence_radius_input.show();
    geofence_submit_btn.show();
    geofence_coord_input.val(e.latlng.lat + ',' + e.latlng.lng);
  });

  // radius range selection events
  $("#geofence_radius").on('input', function () {
    $(this).trigger('change');
  });
  $("#geofence_radius").on('change', function (e){
      $("#radius_value_label").text(e.target.value + ' km');
      if (!geofence_map.hasLayer(geofence_center_marker)){
        return;
      }
      geofence_circle.setRadius(e.target.value * 1000);
      geofence_circle.addTo(geofence_map);
      geofence_radius_input.show();
      geofence_submit_btn.show();
  });
</script>
{% endblock %}

ridecasa/templates/settings/security.html
{% extends "settings/layout.html" %}
{% block settings_content %}
<div class="section">
  <div class="is-grouped is-grouped-centered">
    {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="label flash_{{category}}">{{ message }}</div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    <div class="section">
      <h5 class="title is-5 is-spaced">
        <span>Change E-mail Address</span>
      </h5>
      <form action="" method="post" novalidate>
        <h5 class="title is-5 is-spaced">
        </h5>
        <div class="field">
          <div class="label">
            {{ form.email.label }}
          </div>
          <div class="control">
            {{ form.email(size=32, class_="input") }}
          </div>
          {% for error in form.email.errors %}
          <span style="color: red;">{{ error }}</span>
          {% endfor %}
        </div>
    </div>
    <div class="section">
      <h5 class="title is-5 is-spaced">
        <span>Change Password</span>
      </h5>
      <div class="field">
        <div class="label">
          {{ form.new_password.label }}
        </div>
        <div class="control">
          {{ form.new_password(size=32, class_="input") }}
        </div>
        {% for error in form.new_password.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
      </div>
      <div class="field">
        <div class="label">
          {{ form.repassword.label }}
        </div>
        <div class="control">
          {{ form.repassword(size=42, class_="input") }}
        </div>
        {% for error in form.repassword .errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
      </div>
      <div class="field">
        <div class="label">
          {{ form.current_password.label }}
        </div>
        <div class="control">
          {{ form.current_password(size=42, class_="input") }}
        </div>
        {% for error in form.current_password.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
      </div>
    </div>
    <div class="field has-addons has-addons-right">
      <div class="control has-addons has-addons-right">
        {{ form.submit(class_="button is-link") }}
      </div>
    </div>
    {{ form.hidden_tag() }}
    {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="label flash_{{category}}">{{ message }}</div>
    {% endfor %}
    {% endif %}
    {% endwith %}
      </form>
  </div>
</div>
{% endblock %}