ridecasa/home/views.py
from datetime import datetime
from dateutil.relativedelta import relativedelta
from flask import (Blueprint, make_response, redirect, render_template,
                   request)
from flask_login import current_user, login_required
from pony.orm import db_session
from pony import orm
from ridecasa.home.forms import ActivityFilterForm
from ridecasa.models import db
from ridecasa.util import get_user_prefs

home_blueprint = Blueprint('home', __name__)


@home_blueprint.route('/', methods=['GET', 'POST'])
@db_session
def summary():
    if not current_user.is_authenticated:
        return redirect('/login')

    prefs = get_user_prefs(current_user.id)
    # default to selecting current year/month
    selected_year = prefs.home_filter_selected_year
    if not selected_year:
        selected_year = str(datetime.utcnow().year)
    selected_month = prefs.home_filter_selected_month
    if not selected_month:
        selected_month = str(datetime.utcnow().month)

    form = ActivityFilterForm()
    if request.method == 'POST':
        selected_year = form.year.data
        selected_month = form.month.data
    # Fetch years from activities for filtering list of activities
    form.year.choices = orm.select((str(a.startTime.year),
                                    str(a.startTime.year)) for a
                                   in db.Activity
                                   if a.user.id == current_user.id)[:]
    form.year.choices = form.year.choices.to_list()
    form.year.choices.sort(reverse=True)
    # Add additional options to the menu
    form.year.choices = ([('all', 'All')] + form.year.choices
                         + [('1yr', '1 Year')] + [('6mo', '6 Months')]
                         + [('1mo', '1 Month')])
    # day, month, year
    chart_x_axis_unit = 'year'
    if selected_year == 'all':
        # select all activities
        activities_summary = orm.select((a.startTime.year, 1, 1,
                                         sum(a.distanceMeters))
                                        for a in db.Activity
                                        # sort by year only
                                        if a.user.id == current_user.id
                                        ).order_by(lambda a, y, m, d: y)
        activities = orm.select(a for a in db.Activity
                                if a.user.id == current_user.id)
        chart_x_axis_unit = 'year'
    # 1 year filter
    elif selected_year == '1yr':
        date_delta = datetime.utcnow() + relativedelta(months=-13)
        activities_summary = orm.select((a.startTime.year, a.startTime.month,
                                         1, sum(a.distanceMeters))
                                        for a in db.Activity
                                        if a.user.id == current_user.id and
                                        # sort by munging year and month
                                        a.startTime >= date_delta
                                        ).order_by(lambda a, y, m, d: y * 100 + m)
        activities = orm.select(a for a in db.Activity
                                if a.user.id == current_user.id and
                                a.startTime >= date_delta)
        chart_x_axis_unit = 'month'
    # 1 month filter
    elif selected_year == '1mo':
        date_delta = datetime.utcnow() + relativedelta(months=-1)
        activities_summary = orm.select((a.startTime.year, a.startTime.month,
                                         a.startTime.day, sum(a.distanceMeters))
                                        for a in db.Activity
                                        if a.user.id == current_user.id and
                                        # sort by munging month and day
                                        a.startTime >= date_delta
                                        ).order_by(lambda a, y, m, d: m * 100 + d)
        activities = orm.select(a for a in db.Activity
                                if a.user.id == current_user.id and
                                a.startTime >= date_delta)
        chart_x_axis_unit = 'day'
    # 6 month filter
    elif selected_year == '6mo':
        date_delta = datetime.utcnow() + relativedelta(months=-6)
        activities_summary = orm.select((a.startTime.year, a.startTime.month,
                                         1, sum(a.distanceMeters))
                                        for a in db.Activity
                                        if a.user.id == current_user.id and
                                        # sort by munging year and month
                                        a.startTime >= date_delta
                                        ).order_by(lambda a, y, m, d: y * 100 + m)
        activities = orm.select(a for a in db.Activity
                                if a.user.id == current_user.id and
                                a.startTime >= date_delta)
        chart_x_axis_unit = 'month'
    else:
        # Make sure that there are activities in the selected month for the
        # selected year
        if (selected_month == 'all' or selected_month not in
                orm.select(str(a.startTime.month) for a in db.Activity if
                           str(a.startTime.year) == selected_year)):
            # select only activities in the chosen year
            activities_summary = orm.select((a.startTime.year,
                                             a.startTime.month, 1,
                                             sum(a.distanceMeters))
                                            for a in db.Activity
                                            if a.user.id == current_user.id and
                                            # sort by munging year and month
                                            str(a.startTime.year) == selected_year
                                            ).order_by(lambda a, y, m, d: y * 100 + m)
            activities = orm.select(a for a in db.Activity
                                    if a.user.id == current_user.id and
                                    str(a.startTime.year) == selected_year)
            chart_x_axis_unit = 'month'
        else:
            # select only activities in the chosen year and month
            activities_summary = orm.select((a.startTime.year,
                                            a.startTime.month, a.startTime.day,
                                            sum(a.distanceMeters))
                                            for a in db.Activity
                                            if a.user.id == current_user.id and
                                            str(a.startTime.year) == selected_year and
                                            # sort by day only
                                            str(a.startTime.month) == selected_month
                                            ).order_by(lambda a, y, m, d: d)
            activities = orm.select(a for a in db.Activity
                                    if a.user.id == current_user.id and
                                    str(a.startTime.year) == selected_year and
                                    str(a.startTime.month) == selected_month)
            chart_x_axis_unit = 'day'
    # Sort and remove duplicates from the list of months.
    activity_months = orm.select(a.startTime for a in db.Activity if
                                 str(a.startTime.year) == selected_year and
                                 a.user.id == current_user.id)
    form.month.choices = sorted([(a.month,
                                  a.strftime('%b')) for a in
                                 activity_months], key=lambda x: x[0])
    form.month.choices = list(dict.fromkeys(form.month.choices))
    form.month.choices.insert(0, ('all', 'All'))
    # set the year and month as selected in the drop list
    form.month.data = selected_month
    form.year.data = selected_year

    total_summary = {
        'activities': len(orm.select(a for a in db.Activity
                                     if a.user.id == current_user.id)),
        'distanceMeters': orm.sum(a.distanceMeters for a in db.Activity
                                  if a.user.id == current_user.id),
        'time': orm.sum(a.totalTimeSecs for a in db.Activity
                        if a.user.id == current_user.id),
    }
    if total_summary['activities']:
        num_activities = len(orm.select(a for a in db.Activity
                                        if a.user.id == current_user.id))
        sum_speeds = orm.sum(a.avg_speed for a in db.Activity
                             if a.user.id == current_user.id)
        total_summary['speed'] = round(sum_speeds / num_activities, 1)
    else:
        total_summary['speed'] = 0.0

    resp = make_response(render_template('home/summary.html', form=form,
                                         activities=activities,
                                         total_summary=total_summary,
                                         activities_summary=activities_summary,
                                         chart_x_axis_unit=chart_x_axis_unit,
                                         selected_tab='summary'))
    prefs.home_filter_selected_year = selected_year
    prefs.home_filter_selected_month = selected_month
    return resp


@home_blueprint.route('/monthly', methods=['GET', 'POST'])
@db_session
@login_required
def monthly():
    years = orm.select(str(a.startTime.year) for a
                       in db.Activity
                       if a.user.id == current_user.id)[:]
    total_dicts = []

    months = ('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep',
              'Oct', 'Nov', 'Dec')
    max_month_distance = 0
    for year in years:
        year_dict = {
            'year': year,
            'months': {},
            'total': 0,
        }
        activities_for_year = orm.select((a.startTime.month, a.distanceMeters)
                                         for a in db.Activity

ridecasa/user/views.py
import os
import tempfile
from flask import (Blueprint, redirect, render_template,
                   request)
from flask_login import current_user
from pony.orm import db_session
from pony import orm
from flask_login import login_required
from werkzeug.utils import secure_filename
from ridecasa.tasks import import_file
from ridecasa.util import extract_archive
from ridecasa.models import db

user_blueprint = Blueprint('user', __name__,
                           template_folder='templates')


@user_blueprint.route('/upload', methods=['POST'])
@login_required
def file_upload():
    # allow setting a subdir in /tmp for cases where importer and web backend
    # are different containers
    if (tmp_dir := os.environ.get('RIDECASA_TMP_DIR')) is None:
        tmp_dir = '/tmp'
    dest_dir = tempfile.mkdtemp(prefix=f"{tmp_dir}/tmp_ridecasa_{current_user.id}")

    # handle multiple files, or one
    files = []
    overwrite = True if request.form.get('overwrite') == 'True' else False
    for file in request.files.getlist('file'):
        filename = os.path.join(dest_dir, (str(current_user.id) + '_'
                                           + secure_filename(file.filename)))
        file.save(filename)
        files += extract_archive(filename, dest_dir)
    for file in files:
        import_file(file, current_user.id, overwrite)

    return redirect('/')


@user_blueprint.route('/messages')
@db_session
@login_required
def messages():
    msgs = orm.select(m for m in db.UserMessage
                      if m.user.id == current_user.id
                      ).order_by(orm.desc(db.UserMessage.msg_date))
    return render_template('user/messages.html', msgs=msgs)

ridecasa/templates/layout.html
<!DOCTYPE html>
<html class="has-background-grey-dark">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ride Casa</title>
    {% if current_user.is_authenticated %}
    <script nonce="{{ csp_nonce() }}" type="text/javascript" src="/static/js/jquery/jquery.min.js"></script>
    {% endif %}
    <link rel="stylesheet" href={{ url_for('static',filename='css/bulma.min.css') }}>
    <link rel="stylesheet" href={{ url_for('static',filename='css/main.css') }}>
    <link rel="icon" type="image/svg+xml" href="{{ url_for('static', filename='img/ridecasa_logo.svg') }}">
    {% block head %}
    {% endblock %}

    <header>
      <nav class="navbar is-fixed-top is-success" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <a class="navbar-item" href="{{ url_for('home.summary')}}">
            <figure class="image is-32x32">
              <img src="{{ url_for('static', filename='img/ridecasa_logo.svg') }}" />
            </figure>
            <h1 class="title has-text-dark">Ride Casa</h1></a>
          <h3 class="navbar-item has-text-dark">Alpha</h3>
          <a role="button" class="navbar-burger has-text-dark  is-transparent" aria-label="menu" aria-expanded="false" data-target="navbar_main">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
        <div id="navbar_main" class="navbar-menu">
          <div class="navbar-start">
            <p class="has-text-dark is-size-7"><a href="mailto:~craftyguy/ridecasa@lists.sr.ht?subject=<bug report>">[Report a problem]</p>
          </div>
          <div class="navbar-end">
            {% if current_user.is_authenticated %}
            <div class="navbar-item has-dropdown is-hoverable has-text-dark">
              <a class="navbar-link has-text-dark">
                <strong>{{ current_user.username }}</strong>
              </a>
              <div class="navbar-dropdown">
                <a class="navbar-item is-hoverable has-text-dark" href="{{ url_for('user.messages') }}">Messages</a>
                <a class="navbar-item is-hoverable has-text-dark" href="{{ url_for('settings.general') }}">Settings</a>
                <a class="navbar-item is-hoverable has-text-dark" href="{{ url_for('auth.logout') }}">Log out</a>
              </div>
            </div>
            <div class="navbar-item">
              <a class="button is-link toggle-modal" ><strong>+ Upload</strong></a>
            </div>
            {% else %}
            <div class="navbar-item">
              <div class="buttons">
                <a class="button is-link" href="{{ url_for('auth.signup') }}"><strong>Sign up</strong></a>
                <a class="button is-light" href="{{ url_for('auth.login') }}">Log in </a>
              </div>
            </div>
            {% endif %}
          </div>
        </div>
      </nav>
      {% if current_user.is_authenticated %}
      <!-- File importing modal -->
      <div class="modal" id="import_files_modal">
        <div class="modal-background"></div>
        <div class="modal-card">
          <form id="import_form" action="{{ url_for('user.file_upload')}}" method="POST" enctype="multipart/form-data">
            <header class="modal-card-head">
              <p class="modal-card-title">Upload File(s)</p>
              <button class="delete toggle-modal" aria-label="close"></button>
            </header>
            <section class="modal-card-body" style="overflow:hidden">
              <div class="box" id="files_list" style="display:none; overflow-y: scroll; height: 200px"></div>
              <div class="field has-addons">
                <div class="file  has-name is-fullwidth">
                  <label class="file-label">
                    <input class="file-input" type="file" name="file" id="import_file" accept=".fit,.tcx,.zip" multiple>
                    <span class="file-cta" >
                      <span class="file-icon">
                        <i class="fas fa-upload"></i>
                      </span>
                      <span class="file-label">Choose file(s) to upload...</span>
                    </span>
                  </label>
                </div>
              </div>
            </section>
            <footer class="modal-card-foot">
              <section>
                <div class="content is-pulled-left">
                  <p>
                    Supported file type(s):
                    <div class="tags">
                      <span class="tag is-link is-rounded are-medium">.fit</span>
                      <span class="tag is-link is-rounded are-medium">.tcx</span>
                    </div>
                  </p>
                  <p>Zip files containing the above supported file type(s) are also allowed.</p>
                  <p>Max size of selected files: 100MB</p>
                  <p>
                    <button type="submit is-success" value="Upload" class="button is-link" form="import_form">Upload</button>
                    <button class="button toggle-modal">Cancel</button>
                  </p>
                  <p class="control">
                    <label class="checkbox">
                      <input type="checkbox" name="overwrite" value="True">
                      Overwrite existing activities?</input>
                    </label>
                  </p>

                </div>
              </section>
            </footer>
          </form>
        </div>
      </div>
      {% endif %}

      {% if current_user.is_authenticated %}
      <script nonce="{{ csp_nonce() }}">
        $(document).ready(function() {

          // Check for click events on the navbar burger icon
          $(".navbar-burger").click(function() {

            // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
            $(".navbar-burger").toggleClass("is-active");
            $(".navbar-menu").toggleClass("is-active");

          });
          // This provides a method for toggling the files importing modal, and
          // attaches to any elements with the 'toggle-modal' class
          var modal = document.getElementById('import_files_modal');
          var elements = document.getElementsByClassName('toggle-modal');
          for (var i = 0; i < elements.length; i++) {
            elements[i].addEventListener('click', function(){
              modal.classList.toggle('is-active');
            });
          }
          // Display list of files to be imported when user selects them
          var file = document.getElementById("import_file");
          file.onchange = function(){
            var files_list = document.getElementById('files_list');
            if(file.files.length > 0){
              files_list.style.display = 'block';
              // Clear out any previously selected files from the list
              document.getElementById('files_list').innerHTML = '';
              for (i=0; i<file.files.length; i++){
                document.getElementById('files_list').innerHTML += file.files[i].name + "<br>";
              }
            } else {
              files_list.style.display = 'none';
            }
          };
        });
      </script>
              {% endif %}
    </header>
  </head>

  <body class="has-navbar-fixed-top">
    <div id="wrapper">
      <div class="container is-desktop">
        <div class="has-background-light">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>

    <footer class="footer is-success hero">
      <div class="content has-text-centered has-text-dark">
        <p>
          <strong>Ride Casa</strong> by Clayton Craft. The source code is licensed
          <a href="https://www.gnu.org/licenses/gpl-3.0.html"><u>GPLv3</u></a>, and is
          <a href="https://git.sr.ht/~craftyguy/ridecasa"><u>available on sourcehut</u></a>.
          {% if config['APP_VERSION'] %}
          <span class="is-pulled-right is-size-7">
            Version: <a href="https://git.sr.ht/~craftyguy/ridecasa/commit/{{ config['APP_VERSION'] }}">{{ config['APP_VERSION'] }}</a>
          </span>
          {% endif %}
        </p>
      </div>
    </footer>

  </body>
</html>