ridecasa/home/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField


class ActivityFilterForm(FlaskForm):
    year = SelectField('Year', id='formYearSelect')
    month = SelectField('Month', id='formMonthSelect')

ridecasa/home/views.py
from datetime import datetime
from dateutil.relativedelta import relativedelta
from flask import (Blueprint, make_response, redirect, render_template,
                   request)
from flask_login import current_user, login_required
from pony.orm import db_session
from pony import orm
from ridecasa.home.forms import ActivityFilterForm
from ridecasa.models import db
from ridecasa.util import get_user_prefs

home_blueprint = Blueprint('home', __name__)


@home_blueprint.route('/', methods=['GET', 'POST'])
@db_session
def summary():
    if not current_user.is_authenticated:
        return redirect('/login')

    prefs = get_user_prefs(current_user.id)
    # default to selecting current year/month
    selected_year = prefs.home_filter_selected_year
    if not selected_year:
        selected_year = str(datetime.utcnow().year)
    selected_month = prefs.home_filter_selected_month
    if not selected_month:
        selected_month = str(datetime.utcnow().month)

    form = ActivityFilterForm()
    if request.method == 'POST':
        selected_year = form.year.data
        selected_month = form.month.data
    # Fetch years from activities for filtering list of activities
    form.year.choices = orm.select((str(a.startTime.year),
                                    str(a.startTime.year)) for a
                                   in db.Activity
                                   if a.user.id == current_user.id)[:]
    form.year.choices = form.year.choices.to_list()
    form.year.choices.sort(reverse=True)
    # Add additional options to the menu
    form.year.choices = ([('all', 'All')] + form.year.choices
                         + [('1yr', '1 Year')] + [('6mo', '6 Months')]
                         + [('1mo', '1 Month')])
    # day, month, year
    chart_x_axis_unit = 'year'
    if selected_year == 'all':
        # select all activities
        activities_summary = orm.select((a.startTime.year, 1, 1,
                                         sum(a.distanceMeters))
                                        for a in db.Activity
                                        # sort by year only
                                        if a.user.id == current_user.id
                                        ).order_by(lambda a, y, m, d: y)
        activities = orm.select(a for a in db.Activity
                                if a.user.id == current_user.id)
        chart_x_axis_unit = 'year'
    # 1 year filter
    elif selected_year == '1yr':
        date_delta = datetime.utcnow() + relativedelta(months=-13)
        activities_summary = orm.select((a.startTime.year, a.startTime.month,
                                         1, sum(a.distanceMeters))
                                        for a in db.Activity
                                        if a.user.id == current_user.id and
                                        # sort by munging year and month
                                        a.startTime >= date_delta
                                        ).order_by(lambda a, y, m, d: y * 100 + m)
        activities = orm.select(a for a in db.Activity
                                if a.user.id == current_user.id and
                                a.startTime >= date_delta)
        chart_x_axis_unit = 'month'
    # 1 month filter
    elif selected_year == '1mo':
        date_delta = datetime.utcnow() + relativedelta(months=-1)
        activities_summary = orm.select((a.startTime.year, a.startTime.month,
                                         a.startTime.day, sum(a.distanceMeters))
                                        for a in db.Activity
                                        if a.user.id == current_user.id and
                                        # sort by munging month and day
                                        a.startTime >= date_delta
                                        ).order_by(lambda a, y, m, d: m * 100 + d)
        activities = orm.select(a for a in db.Activity
                                if a.user.id == current_user.id and
                                a.startTime >= date_delta)
        chart_x_axis_unit = 'day'
    # 6 month filter
    elif selected_year == '6mo':
        date_delta = datetime.utcnow() + relativedelta(months=-6)
        activities_summary = orm.select((a.startTime.year, a.startTime.month,
                                         1, sum(a.distanceMeters))
                                        for a in db.Activity
                                        if a.user.id == current_user.id and
                                        # sort by munging year and month
                                        a.startTime >= date_delta
                                        ).order_by(lambda a, y, m, d: y * 100 + m)
        activities = orm.select(a for a in db.Activity
                                if a.user.id == current_user.id and
                                a.startTime >= date_delta)
        chart_x_axis_unit = 'month'
    else:
        # Make sure that there are activities in the selected month for the
        # selected year
        if (selected_month == 'all' or selected_month not in
                orm.select(str(a.startTime.month) for a in db.Activity if
                           str(a.startTime.year) == selected_year)):
            # select only activities in the chosen year
            activities_summary = orm.select((a.startTime.year,
                                             a.startTime.month, 1,
                                             sum(a.distanceMeters))
                                            for a in db.Activity
                                            if a.user.id == current_user.id and
                                            # sort by munging year and month
                                            str(a.startTime.year) == selected_year
                                            ).order_by(lambda a, y, m, d: y * 100 + m)
            activities = orm.select(a for a in db.Activity
                                    if a.user.id == current_user.id and
                                    str(a.startTime.year) == selected_year)
            chart_x_axis_unit = 'month'
        else:
            # select only activities in the chosen year and month
            activities_summary = orm.select((a.startTime.year,
                                            a.startTime.month, a.startTime.day,
                                            sum(a.distanceMeters))
                                            for a in db.Activity
                                            if a.user.id == current_user.id and
                                            str(a.startTime.year) == selected_year and
                                            # sort by day only
                                            str(a.startTime.month) == selected_month
                                            ).order_by(lambda a, y, m, d: d)
            activities = orm.select(a for a in db.Activity
                                    if a.user.id == current_user.id and
                                    str(a.startTime.year) == selected_year and
                                    str(a.startTime.month) == selected_month)
            chart_x_axis_unit = 'day'
    # Sort and remove duplicates from the list of months.
    activity_months = orm.select(a.startTime for a in db.Activity if
                                 str(a.startTime.year) == selected_year and
                                 a.user.id == current_user.id)
    form.month.choices = sorted([(a.month,
                                  a.strftime('%b')) for a in
                                 activity_months], key=lambda x: x[0])
    form.month.choices = list(dict.fromkeys(form.month.choices))
    form.month.choices.insert(0, ('all', 'All'))
    # set the year and month as selected in the drop list
    form.month.data = selected_month
    form.year.data = selected_year

    total_summary = {
        'activities': len(orm.select(a for a in db.Activity
                                     if a.user.id == current_user.id)),
        'distanceMeters': orm.sum(a.distanceMeters for a in db.Activity
                                  if a.user.id == current_user.id),
        'time': orm.sum(a.totalTimeSecs for a in db.Activity
                        if a.user.id == current_user.id),
    }
    if total_summary['activities']:
        num_activities = len(orm.select(a for a in db.Activity
                                        if a.user.id == current_user.id))
        sum_speeds = orm.sum(a.avg_speed for a in db.Activity
                             if a.user.id == current_user.id)
        total_summary['speed'] = round(sum_speeds / num_activities, 1)
    else:
        total_summary['speed'] = 0.0

    resp = make_response(render_template('home/summary.html', form=form,
                                         activities=activities,
                                         total_summary=total_summary,
                                         activities_summary=activities_summary,
                                         chart_x_axis_unit=chart_x_axis_unit,
                                         selected_tab='summary'))
    prefs.home_filter_selected_year = selected_year
    prefs.home_filter_selected_month = selected_month
    return resp


@home_blueprint.route('/monthly', methods=['GET', 'POST'])
@db_session
@login_required
def monthly():
    years = orm.select(str(a.startTime.year) for a
                       in db.Activity
                       if a.user.id == current_user.id)[:]
    total_dicts = []

    months = ('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep',
              'Oct', 'Nov', 'Dec')
    max_month_distance = 0
    for year in years:
        year_dict = {
            'year': year,
            'months': {},
            'total': 0,
        }
        activities_for_year = orm.select((a.startTime.month, a.distanceMeters)
                                         for a in db.Activity

ridecasa/templates/home/layout.html
{% extends "layout.html" %}
{% block head %}
{% endblock %}

{% block content %}
<section class="section">
  <div class="tabs">
    <ul>
      <li {% if selected_tab == "summary" %}class="is-active"{% endif %}><a href="{{ url_for('home.summary') }}">Summary</a></li>
      <li {% if selected_tab == "monthly" %}class="is-active"{% endif %}><a href="{{ url_for('home.monthly') }}">Monthly Totals</a></li>
    </ul>
  </div>
</section>
{% block home_content %}
{% endblock %}
{% endblock %}

ridecasa/templates/home/monthly.html
{% extends "home/layout.html" %}
{% block head %}
{% endblock %}

{% block home_content %}
<section class="hero is-success is-medium">
  <div class="container">
  </div>
</section>
<section class="section centered">
  {% if total_dicts %}
  <div class="table-container">
    <table class="table is-hoverable is-fullwidth table-container" id="monthly_table">
      <thead>
        <tr>
          <th></th>
          {% for month in months %}
          <th>{{month}}</th>
          {% endfor %}
          <th>Total</th>
        </tr>
      </thead>
      <tbody>
        {% for year_dict in total_dicts %}
        <tr>
          <th>{{year_dict['year']}}</th>
          {% for m in range(12) %}
          <th>
            {% if m in year_dict['months'] %}
            <div class="centered">
              {% set percentage = year_dict['months'][m] / max_month_distance %}
              {% set dimension = 45 *  percentage %}
              <div class="circle" style="background-color: #70C1B3; width: {{dimension}}px; height: {{dimension}}px; opacity: {{percentage}}"></div>
              <p class="has-text-centered" style="font-size:.6em">{{year_dict['months'][m]|round(2)|string + ' km'}}</p>
            </div>
            {% endif %}
          </th>
          {% endfor %}
          <th>{{year_dict['total']}} km</th>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% else %}
  <div class="label is-medium" style="text-align:center">No activies here! Use the upload button above to start uploading activities!</div>
  {% endif %}
</section>


<script nonce="{{ csp_nonce() }}">
</script>

{% endblock %}

ridecasa/templates/home/summary.html
{% extends "home/layout.html" %}
{% block head %}
    <script type="text/javascript" src="/static/js/jquery/jquery.min.js" nonce="{{ csp_nonce() }}"></script>
    <script type="text/javascript" src="/static/js/jquery/jquery.canvaswrapper.js" nonce="{{ csp_nonce() }}"></script>
    <script type="text/javascript" src="/static/js/jquery/jquery.colorhelpers.js" nonce="{{ csp_nonce() }}"></script>
    <script type="text/javascript" src="/static/js/moment-with-locales.min.js" nonce="{{ csp_nonce() }}"></script>
    <script type="text/javascript" src="/static/js/jquery/jquery.flot.js" nonce="{{ csp_nonce() }}"></script>
    <script type="text/javascript" src="/static/js/jquery/jquery.flot.saturated.js" nonce="{{ csp_nonce() }}"></script>
    <script type="text/javascript" src="/static/js/jquery/jquery.flot.browser.js" nonce="{{ csp_nonce() }}"></script>
    <script type="text/javascript" src="/static/js/jquery/jquery.flot.drawSeries.js" nonce="{{ csp_nonce() }}"></script>
    <script type="text/javascript" src="/static/js/jquery/jquery.flot.uiConstants.js" nonce="{{ csp_nonce() }}"></script>
    <script type="text/javascript" src="/static/js/jquery/jquery.flot.resize.js" nonce="{{ csp_nonce() }}"></script>
    <script type="text/javascript" src="/static/js/jquery/jquery.flot.time.js" nonce="{{ csp_nonce() }}"></script>
    <script type="text/javascript" src="/static/js/jquery/jquery.flot.touchNavigate.js" nonce="{{ csp_nonce() }}"></script>
    <script type="text/javascript" src="/static/js/jquery/jquery.flot.hover.js" nonce="{{ csp_nonce() }}"></script>
    <script type="text/javascript" src="/static/js/jquery/jquery.flot.touch.js" nonce="{{ csp_nonce() }}"></script>
    <script type="text/javascript" src="/static/js/jquery/jquery.tablesorter.js" nonce="{{ csp_nonce() }}"></script>
    <script type="text/javascript" src="/static/js/jquery/jquery.tablesorter.widgets.js" nonce="{{ csp_nonce() }}"></script>
    <link rel="stylesheet" href="{{ url_for('static',filename='css/tablesorter.theme.ice.css') }}">
{% endblock %}

{% block home_content %}
<section>
  <div class="container">
    <nav class="level">
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Total Avg Speed (km/hr)</p>
          <p class="title">{{ total_summary['speed']|round(2) }}</p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Total Distance (km)</p>
          <p class="title">{{ (total_summary['distanceMeters'] / 1000.0)|round(2) }}</p>
        </div>
      </div>
      <div class="level-item has-text-centered">
        <div>
          <p class="heading">Total Moving Time</p>
          <p class="title">{{ (total_summary['time'] / 3600)|int() }}h {{((total_summary['time'] % 3600) / 60)|int()}}m</p>
        </div>
      </div>
    </nav>
  </div>
</section>
<section class="section">
  {% if total_summary['activities'] %}
  <div class="field">
  {% if activities_summary|length > 0 %}
    <div class="label is-small" style="text-align:center">Distance (km)</div>
    <div class="field" id="chart_section">
      <div id="chartid" style="height:360px" class="box"></div>
    </div>
  {% else %}
    <div class="label is-medium" style="text-align:center">No activities in the selected date range</div>
  {% endif %}
  </div>
  <div class="field">
    <div class="container">
      <form id="formDateFilter" action="" method="post" novalidate>
        <div class="field is-grouped">
          <div class="select">{{ form.year(class_="select") }}</div>
          <div class="select">{{ form.month(class_="select") }}</div>
        </div>
      </form>
    </div>
  </div>
  {% if activities_summary|length > 0 %}
  <div class="field">
    <table class="tablesorter-ice" id="activity_table">
      <thead>
        <tr>
          <th>Activity</th>
          <th>Date</th>
          <th>Distance (km)</th>
          <th>Avg Speed (km/hr)</th>
        </tr>
      </thead>
      {% for activity in activities %}
      <tr>
        <th>{{activity.sport}}</th>
        <th><a href="{{ '/activity/' + activity.activity_id|string}}">
            <script nonce="{{ csp_nonce() }}">
              document.write(moment("{{activity.startTime}}").format('LLL'));
            </script>
          </a>
        </th>
        <th>{{(activity.distanceMeters / 1000.0)|round(2)}}</th>
        <th>{{(activity.avg_speed)|round(2)}}</th>
      </tr>
      {% endfor %}
    </table>
  </div>
  {% endif %}
  {% else %}
  <div class="label is-medium" style="text-align:center">No activies here! Use the upload button above to start uploading activities!</div>
  {% endif %}
</section>


<script nonce="{{ csp_nonce() }}">
  function gd(year, month, day) {
    return new Date(year, month - 1, day).getTime();
  }

  var formYearSelect = document.getElementById("formYearSelect");
  var formMonthSelect = document.getElementById("formMonthSelect");
  var formDateFilter = document.getElementById("formDateFilter");
  if (formMonthSelect){
    formMonthSelect.onchange = function (){
      formDateFilter.submit();
    }
  }
  if (formMonthSelect){
    formYearSelect.onchange =  function (){
      formDateFilter.submit();
    }
  }

  chart_dataset = [
    {% for activity in activities_summary %}
    [new Date({{activity[0]}}, {{activity[1]}}-1, {{activity[2]}}).getTime(),{{(activity[3] / 1000.0)|round(2)}}],
    {% endfor %}
  ];

  var minTime;
  var maxTime;

  for (i=0; i<chart_dataset.length; i++){
    time = chart_dataset[i][0];
    if (!maxTime || time > maxTime){
      maxTime = time;
    }
    if (!minTime || time < minTime){
      minTime = time;
    }
  }
  if (maxTime == minTime) {
    padding = 1000 * 3600 * 24;  // miliseconds in day
    if ("{{chart_x_axis_unit}}" == "month"){
      padding *= 7 * 2;  // 2 weeks;
    } else if ("{{chart_x_axis_unit}}" == "year"){
      padding *= 7 * 4 * 6;  // ~6 months;
    }
    minTime -= padding;
    maxTime += padding;
  }
  if (chart_dataset.length == 1) {
    chart_dataset.push([minTime, 0]);
    chart_dataset.push([maxTime, 0]);
  }

  if (chart_dataset.length > 0){
    // totalWidth = (numBars * barSize) + ((1 + numBars) * barSize), solved for barSize
    // from: https://stackoverflow.com/a/25367550
    var total_time = moment.duration(maxTime - minTime);
    if ("{{chart_x_axis_unit}}" == "month"){
      total_time = total_time.asMonths();
    } else if ("{{chart_x_axis_unit}}" == "day"){
      total_time = total_time.asDays();
    } else if ("{{chart_x_axis_unit}}" == "year"){
      total_time = total_time.asYears();
    }
    var barWidth = (total_time / ((2 * chart_dataset.length) + 1));

    var chartid = $.plot($("#chartid"), [chart_dataset], {
      legend: {
        show: false
      },
      grid: {
        hoverable: true,
        clickable: true,
      },
      series: {
        bars: {
          show: true,
          barWidth: barWidth,
          fill: true,
          fillColor: { colors: [ { opacity: 1.0 }, { opacity: 1.0 } ] },
          align: 'center',
        },
      },
      colors: ["#70C1B3"],
      xaxis: {
        mode: 'time',
        timezone: 'browser',
        minTickSize: [1, "{{chart_x_axis_unit}}"],
        tickLength: 0,
        timeBase: "milliseconds",
      },
    });

    $("<div id='charttooltip'></div>").css({
      position: "absolute",
      display: "none",
      border: "1px solid #fdd",
      padding: "2px",
      "background-color": "#fee",
      opacity: 0.80
    }).appendTo("body");

    $("#chartid").bind("plothover", function (event, pos, item) {
      if (item) {
        var distance = item.datapoint[1].toFixed(2);
        $("#charttooltip").html(distance + " km")
          .css({top: item.pageY, left: item.pageX})
          .fadeIn(50);
      } else {
        $("#charttooltip").hide();
      }
    });

    // Initialize sorting on activity table, sort the date column by default
    // in desc order
    $(function() {
      $("#activity_table").tablesorter({
        sortList: [[1,1]],
        // initialize zebra striping and column styling of the table
        widgets : ["zebra", "columns"],

        widgetOptions : {
          columns_thead : true,
          // include tfoot when adding class names
          columns_tfoot : true
        }
      });
    });

  }
</script>

{% endblock %}